import os
import csv
import uuid
import random
import logging
from datetime import datetime, timedelta
from dotenv import load_dotenv, find_dotenv
from faker import Faker

# Load base config (.env with Docker container paths)
# (先加载基础配置，包含 Docker 容器路径)
load_dotenv(find_dotenv())

# Override with local config if it exists (.env.local with Mac absolute paths)
# (如果本地配置文件存在，用 Mac 绝对路径覆盖，供本地测试使用)
local_env = find_dotenv('.env.local')
if local_env:
    load_dotenv(local_env, override=True)

# Configure logging (配置日志记录器)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# Initialise Faker with Australian locale (使用澳洲本地化 Faker 生成真实感数据)
fake = Faker('en_AU')

# Read target directory from environment variable (从环境变量读取目标落地路径)
TARGET_DIR = os.environ.get(
    "HEALTHCARE_LANDING_DIR",
    "./data/1_landing/healthcare_landing"
)


def generate_daily_healthcare_records() -> str:
    """
    Generates a daily batch of mock healthcare patient records and saves
    them as a CSV file in the healthcare landing directory.
    (生成每日医疗患者记录批次，并保存为 CSV 文件到 healthcare landing 目录)

    Each record represents one version of a patient's insurance state,
    following SCD Type 2 structure with start_date and end_date.
    (每条记录代表患者保险状态的一个版本，采用 SCD Type 2 拉链表结构，
    通过 start_date 和 end_date 追踪历史变化)

    Returns:
        str: The file path of the generated CSV file. (返回生成的 CSV 文件路径)
    """
    try:
        # Ensure landing directory exists (确保落地文件夹存在，不存在则自动创建)
        os.makedirs(TARGET_DIR, exist_ok=True)

        # Generate unique filename using current timestamp, no microseconds
        # (用当前时间戳生成唯一文件名，精确到秒，去掉微秒)
        file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        file_name = f"healthcare_records_{file_timestamp}.csv"
        file_path = os.path.join(TARGET_DIR, file_name)

        # Define CSV headers - SCD Type 2 structure
        # (定义字段头 - SCD Type 2 维度表结构)
        headers = [
            "patient_uuid",      # Unique patient identifier, UUID (唯一患者ID，UUID格式)
            "patient_name",      # Full name generated by Faker (Faker 生成的患者全名)
            "medicare_number",   # 10-digit unique Medicare number (10位唯一医保号码)
            "insurance_plan",    # Insurance tier (保险等级)
            "start_date",        # Date this record version became active (记录生效日期)
            "end_date"           # '9999-12-31' = currently active record (当前有效记录的哨兵日期)
        ]

        # Generate between 900 to 1100 patient records (随机生成 900 到 1100 条患者记录)
        num_rows = random.randint(900, 1100)

        # Sentinel end date for currently active SCD2 records
        # (SCD2 拉链表中表示"当前有效"的哨兵结束日期)
        active_end_date = "9999-12-31"

        # Use a set to guarantee medicare_number uniqueness across all rows
        # (用 set 追踪已用号码，确保每条记录的 medicare_number 全局唯一，避免碰撞)
        used_medicare_numbers = set()

        with open(file_path, mode="w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(headers)

            for _ in range(num_rows):
                # Generate unique patient UUID (生成唯一患者 UUID)
                patient_uuid = str(uuid.uuid4())

                # Generate unique 10-digit medicare number using rejection sampling
                # (用拒绝采样法生成唯一的 10 位医保号码：生成后检查是否已存在，重复则重新生成)
                while True:
                    medicare_number = fake.numerify(text="##########")
                    if medicare_number not in used_medicare_numbers:
                        used_medicare_numbers.add(medicare_number)
                        break

                # Patient name from Australian locale Faker (澳洲本地化 Faker 生成患者姓名)
                patient_name = fake.name()

                # Insurance plan distribution (保险计划分布)
                insurance_plan = random.choice(["Basic", "Standard", "Premium", "Uninsured"])

                # Start date: random day within the past year
                # (生效日期：过去一年内随机选择一天，模拟患者状态变更的历史分布)
                random_days_ago = random.randint(1, 365)
                start_date = (
                    datetime.now() - timedelta(days=random_days_ago)
                ).strftime("%Y-%m-%d")

                writer.writerow([
                    patient_uuid,
                    patient_name,
                    medicare_number,
                    insurance_plan,
                    start_date,
                    active_end_date
                ])

        logger.info("Successfully generated healthcare records file (成功生成医疗记录文件)")
        logger.info(f"File path (文件路径): {file_path}")
        logger.info(f"Fields (字段): {headers}")
        logger.info(f"Total rows generated (生成行数): {num_rows}")

        return file_path

    except OSError as e:
        logger.error(f"File system error while generating healthcare data (文件系统错误): {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error during healthcare data generation (数据生成时发生意外错误): {e}")
        raise


if __name__ == "__main__":
    generate_daily_healthcare_records()